[package]
name = "idle"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "nixly-idled"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
smithay-client-toolkit.workspace = true
input = { path = "../input" }
